# Generated by Django 5.0.6 on 2026-03-11 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='vessel',
            old_name='name',
            new_name='vessel_name',
        ),
        migrations.AlterField(
            model_name='vessel',
            name='course',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='mmsi',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vesselevent',
            name='event_type',
            field=models.CharField(choices=[('POSITION_UPDATE', 'Position Update'), ('STOPPED', 'Stopped'), ('ROUTE_CHANGE', 'Route Change'), ('PORT_ENTRY', 'Port Entry'), ('AIS_LOST', 'AIS Lost')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='vesselsubscription',
            unique_together={('user', 'vessel')},
        ),
    ]
